version: '3.8'
services:
  web:
    build: 
      context: .
      args:
        - ODOO_ENTERPRISE_TOKEN=${ODOO_ENTERPRISE_TOKEN}
    container_name: ${ODOO_CONTAINER_NAME:-odoo}
    working_dir: /mnt/repository  # Cambia el directorio de trabajo
    depends_on:
      - db
    ports:
      - "${ODOO_PORT:-8069}:8069"
      - "${DEBUGPY_PORT:-8888}:8888"
    volumes:
      - ./conf:/etc/odoo
      - odoo-web-data:/var/lib/odoo
      - /workspace/extra-addons:/mnt/extra-addons:ro
      - /workspace/repository:/mnt/repository:ro
    environment:
      - HOST=db
      - USER=${PG_USER:-admin}
      - PASSWORD=${PG_PASSWORD:-admin}
    entrypoint: /usr/bin/python3 -m debugpy --listen 0.0.0.0:8888 /usr/bin/odoo -c /etc/odoo/odoo.conf
    command: []
    restart: unless-stopped
