version: '3.8'
services:
  web:
    build: 
      context: .
      args:
        - ODOO_ENTERPRISE_TOKEN=${ODOO_ENTERPRISE_TOKEN}
    container_name: ${ODOO_CONTAINER_NAME:-odoo}
    depends_on:
      - db
    ports:
      - "${ODOO_PORT:-8069}:8069"
    volumes:
      - ./conf:/etc/odoo
      - odoo-web-data:/var/lib/odoo
      - /workspace/extra-addons:/mnt/extra-addons:ro
      - /workspace/repository:/mnt/repository:ro
    environment:
      - HOST=db
      - USER=${PG_USER:-admin}
      - PASSWORD=${PG_PASSWORD:-admin}
    entrypoint: /usr/bin/odoo -c /etc/odoo/odoo.conf
    restart: unless-stopped

  db:
    image: postgres:${PG_VERSION:-14}
    container_name: ${PG_CONTAINER_NAME:-postgres}
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${PG_PASSWORD:-admin}
      - POSTGRES_USER=${PG_USER:-admin}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "${PG_PORT:-5432}:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    restart: unless-stopped

volumes:
  odoo-web-data:
  odoo-db-data:
