version: "3.1"
services:
    enterprise_web15:
        container_name: ${ODOO_CONTAINER_NAME}
        image: odoo:${ODOO_VERSION}
        depends_on:
            - enterprise_db15
        ports:
            - "${ODOO_PORT}:8069"
            - "${DEBUGPY_PORT}:5678"
        volumes:
            - ./config:/etc/odoo
            - web:/var/lib/odoo
            - ${EXTRA_ADDONS}:/mnt/extra-addons
            - ${GITHUB}:/mnt/github
        entrypoint: ${ENTRYPOINT}

    enterprise_db15:
        container_name: ${PG_CONTAINER_NAME}
        image: postgres:${PG_VERSION}
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_PASSWORD=${PG_PASSWORD}
            - POSTGRES_USER=${PG_USER}
            - PGDATA=/var/lib/postgresql/data
        ports:
            - "${PG_PORT}:5432"
        volumes:
            - db:/var/lib/postgresql/data
volumes:
    web:
    db:
